<<<<<<< HEAD
name: Araceli Medina
author: Araceli
baseurl: /
description: theme for jekyll
github: http://www.github.com/Aracelimp
twitter: http://www.twitter.com/
linkedin: https://www.linkedin.com/in/aracelimedina/
email: araceli.mepi@gmail.com

disqus: araceli-medina

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
=======
theme: jekyll-theme-minimal
---
- title: Home
---
social:
    - icon: fa-twitter
      link: "https://twitter.com/AraceliMepi"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/aracelimedina"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/


>>>>>>> 9fe6b755196460265b983116ff5b0d13cf25273d
