baseurl: /ara-mp
description: theme for jekyll
github: http://www.github.com/Aracelimp/AI-study-guide
twitter: http://www.twitter.com/AraceliMepi
linkedin: https://www.linkedin.com/in/aracelimedina/
disqus:  Araceli

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
