# Site settings
title: AI and ML study guide
email: araceli.mepi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My space
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: AraceliMepi
github_username:  Aracelimp

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /projects/:path/
  poetry:
    output: true
    permalink: /ML/:path/


